### ISSUE TITLE
Serve functions.json

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/mailroom#122]
It would be good to serve the version of functions that goflow is using up for the editor to match with.

**Comment by rowanseymour** [comment]
Maybe it hosts all the generated docs (/docs)? Then editor has some where it can link to to see complete docs for everything. Tricky part is that go dependencies are code only.

**Comment by nicpottier** [comment]
We do build and deploy from a package built by goreleaser so including a set of static files wouldn't be very difficult if we want to go that way. Or alternatively we can gzip/include it in the binary using something like packr or statik

**Comment by nicpottier** [comment]
Added.

**Comment by cromulus** [comment]
This is a current problem in the 5.2.6 branch of mailroom releases. Currently, a brand new deploy breaks the new flow editor because the mailroom binary doesn't serve the functions.json or the completions.json files.
