### ISSUE TITLE
Make engine step limit configurable 

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#131]
See https://github.com/nyaruka/goflow/pull/574. Relevant code is at https://github.com/nyaruka/mailroom/blob/master/goflow/engine.go#L14

**Comment by chris-erickson** [comment]
Sorry, should have commented on the new one - what is the fix in the meantime? This is breaking production flows for a lot of people...

**Comment by nicpottier** [comment]
Fixed in v1.0.2

**Comment by nicpottier** [comment]
`MAILROOM_MAX_STEPS_PER_SPRINT` env or `-max-steps-per-sprint infinityplusone`

**Comment by putorti** [comment]
@nicpottier We rely on infinite loops for blocking spammers and keeping our Twilio costs down on repeat texts. Should we set our limit to a billion or what to you recommend to keep our desired cases for this like bot on fire and purgatory?

**Comment by nicpottier** [comment]
No.. this is per sprint, you can loop as long as you want in a flow if they are interacting. (though generally you do still want them to eventually expire) For your spam case you probably only have a step or two at most in that spammer trap.

A sprint is all the stuff that happens BETWEEN interactions, not total # of steps. Number of steps is roughly number of arrows that have been traversed in that sprint until the next wait.

You can set this to over 100, maybe 200 temporarily, but I certainly would not set it to something much higher.

**Comment by putorti** [comment]
Right, sorry, I thought of these cases when thinking of what limit to set and conflated concepts, thanks.
