### ISSUE TITLE
Webhooks that can't be parsed send an empty body

### ISSUE THREAD

**Issue by chris-erickson** [rapidpro/mailroom#133]
When building the webhook body, if you botch the `json` construction it won't really tell you.  It will still fire, but sends an empty body.  Best would be for the editor to validate the syntax live, but short of that, failing and _not_ sending the call would be pretty good.

**Comment by nicpottier** [comment]
This one is kinda a 🤷‍♂ .. I don't think either behavior is perfect while running a flow but bugs in expressions are bugs in expressions. There can be errors in expressions that lead to valid JSON, I'm guessing that in your case your whole body is an expression so its ending up empty. (errors stringify as `""` in expressions)

So I think what we are doing is as good as you can do given an invalid expression really. Firing empty is also easier for users to debug than to not fire at all. (which would lead to people saying we are broken)

**Comment by rowanseymour** [comment]
We just chatted about this a bit more and this is definitely a weird one... but it still seems more consistent with other actions to send the payload. For example if a message body or email body has an error, we still send those. Also seems more likely users would discover if their webhook is broken because the other end starts complaining.

**Comment by chris-erickson** [comment]
Sounds good, I don't think there is a clear "right" way here.  Probably really 💯would be for some amount of expression validation in the editor or other surfacing of the parsing errors in the editor UI, but I'm sure that's not trivial.  Thanks!

**Comment by nicpottier** [comment]
Ya, per usual the simulator is there to help on that stuff, but doing basic expression validation is something that is on the roadmap anywhere where expressions can live.
