### ISSUE TITLE
problem with S3

### ISSUE THREAD

**Issue by FlorentinCONGO** [rapidpro/mailroom#142]
I tried to configure mailroom but i have this erro: `ERRO[0000] s3 bucket not reachable                       error="BadRequest: Bad Request\n\tstatus code: 400, request id: 07D6B0C037DEC57B, host id: 6oJZ9RQMsOthxJxv4FSoaNKv1ST5rHIUPIi8wHJy19ndQnEXYLdvE9MlWRfrQKT7DIzwe6KMfS8=" state=starting`
Could you help me please?

**Comment by nicpottier** [comment]
Have you configured the S3 parameters / config?

**Comment by FlorentinCONGO** [comment]
Hi Mr Pottier. yes i configured it. 

COURIER_S3_REGION= "us-west-1"
COURIER_S3_MEDIA_BUCKET="smsforce"
COURIER_S3_MEDIA_PREFIX="smsforce"
COURIER_AWS_ACCESS_KEY_ID="XXXXXX"
COURIER_AWS_SECRET_ACCESS_KEY="XXXXX"

This parameters was configure but i have same error.

**Comment by nicpottier** [comment]
Well those are settings for COURIER_, not MAILROOM_ so that's probably your problem.

Check the README or do `--help` to see the proper name for the environment variables.
