### ISSUE TITLE
problem with S3 with mailroom

### ISSUE THREAD

**Issue by FlorentinCONGO** [rapidpro/mailroom#143]
I tried to configure mailroom but i have this erro: `ERRO[0000] s3 bucket not reachable error="BadRequest: Bad Request\n\tstatus code: 400, request id: 07D6B0C037DEC57B, host id: 6oJZ9RQMsOthxJxv4FSoaNKv1ST5rHIUPIi8wHJy19ndQnEXYLdvE9MlWRfrQKT7DIzwe6KMfS8=" state=starting`
This is my configuration:

> MAILROOM_S3_REGION= "us-west-1"
> MAILROOM_S3_MEDIA_BUCKET="smsforce"
> MAILROOM_S3_MEDIA_PREFIX="smsforce"
> MAILROOM_AWS_ACCESS_KEY_ID="XXXXXX"
> MAILROOM_AWS_SECRET_ACCESS_KEY="XXXXX"

Could you help me please?

**Comment by nicpottier** [comment]
You likely need to change your S3 endpoint:
  MAILROOM_S3_ENDPOINT

See: https://docs.aws.amazon.com/general/latest/gr/rande.html
