### ISSUE TITLE
Config questions

### ISSUE THREAD

**Issue by cromulus** [rapidpro/mailroom#147]
Hi!
I'm trying to spin up a production instance of the whole Rapidpro system, and I'm a bit confused about mailroom's config.
```
MAILROOM_AUTH_TOKEN: the token clients will need to authenticate web requests (should match setting in RapidPro)
```

What token are you talking about here? Where is it set in Rapidpro?

**Comment by nicpottier** [comment]
Set here:
  https://github.com/nyaruka/rapidpro/blob/master/temba/settings_common.py#L1094

Its just a shared secret between RapidPro and Mailroom
