### ISSUE TITLE
Extra not passed from flow start task to trigger for IVR

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#149]
A user is trying to start an IVR flow from Zapier and not getting the extra passed via the API call  in `@trigger.params`. I think problem is https://github.com/nyaruka/mailroom/blob/1108b20e90bbae3b9b25a138fed1758578b216ad/ivr/ivr.go#L354

**Comment by nicpottier** [comment]
Ya, I think that's right. Question is whether our start has `extra` populated on it, if so then this should be a reasonably easy fix.

**Comment by rowanseymour** [comment]
I think we're good there https://github.com/nyaruka/rapidpro/blob/c258ebc20c99552a4259cde4de2ef1c4ba80e96d/temba/api/v2/serializers.py#L918
