### ISSUE TITLE
Task for interrupting sessions and runs

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#157]
Currently RapidPro interrupts sessions when:

- API call to bulk contact actions endpoint with "interrupt" action (interrupts all runs for each contact, which causes calls to be hungup and sessions to be interrupted)
- Releasing a channel if there are calls using that channel (closes each call which ends its session tho doesn't interrupt the runs)

We don't want RapidPro to have to know about different IVR providers and how to hang up calls.. and ideally RapidPro would let mailroom be solely responsible for interrupting sessions and runs.

We could have a new "interrupt" task which can either:

- Interrupt sessions, runs and calls for a given set of contacts
- Interrupt sessions, runs and calls for a given channel

Or two different tasks?

**Comment by nicpottier** [comment]
I'd vote for the former and have RapidPro look up open connections for a channel when it releases a channel, interrupting just those contacts.

**Comment by nicpottier** [comment]
(IE, it is always on contacts and there is only one task)

**Comment by rowanseymour** [comment]
Two potential downsides there:
 1. Possible that we pass a really large list of contact ids.. not even sure if that's a downside?
 2. If in the future we have non-interrupting flows, then we may have overlapping sessions, and we only want to kill those sessions associated with the channel being released

If 1. isn't an issue but 2. is then we could make it so this task always takes `contact_ids` but may also take optional `channel_id` which limits the sessions interrupted

**Comment by nicpottier** [comment]
Hrmm.. good points and it would be nice to avoid having RapidPro start a task to build up a list of ids to then have to pass on to mailroom. So maybe just having Mailroom be more cleverer does make sense there.

**Comment by rowanseymour** [comment]
What I've got mocked in RP so far is https://github.com/nyaruka/rapidpro/pull/2496/files#diff-48c4ef774f19418e425f28a230c2a004R211

**Comment by nicpottier** [comment]
Have at it in mailroom!

**Comment by rowanseymour** [comment]
Seems fairly straightforward to hook up a new redis task to a method like `models.ExitSessions` but that won't actually hang up calls like we were doing in RP. Have created a new issue to discuss way forward there at https://github.com/nyaruka/mailroom/issues/162

Maybe ok for the time being that the task doesn't do hangups.. because it probably currently doesn't do that in production.

**Comment by nicpottier** [comment]
Completed in https://github.com/nyaruka/mailroom/pull/163
