### ISSUE TITLE
IVR problem

### ISSUE THREAD

**Issue by FlorentinCONGO** [rapidpro/mailroom#159]
Hi everybody, i installed the last version of Rapidpro. I can start flow for message but the flow of IVR doesn't work. I doubt that it is related to mailroom. 
Also, on twilio i have these links: 

example.com/4fb25647-a382-41a7-a913-a12c83f5adbe
https://example.com/mr/ivr/c/4fb25647-a382-41a7-a913-a12c83f5adbe/incoming
https://example.com/c/t/4fb25647-a382-41a7-a913-a12c83f5adbe/receive

but all his links give error 404. 

Can you help me?

Thanks in advance,

**Comment by nicpottier** [comment]
You need to redirect URLs that start with `/c/` and `/mr/` to Courier and Mailroom respectfully.

More here:
  http://rapidpro.github.io/rapidpro/docs/courier/
  http://rapidpro.github.io/rapidpro/docs/mailroom/

**Comment by nicpottier** [comment]
Moved to issue:
  https://github.com/nyaruka/mailroom/issues/159

**Comment by FlorentinCONGO** [comment]
thank you for your prompt reply.

**Comment by Boxroma** [comment]
Hey there.. I am having the same issue i managed to redirect URLs that start with /c/ and /mr/ to Courier and Mailroom respectfully but i am still having 404 errors when creating a flow. 
I dug deeper and tried to make requests directly to mailroom and this was my response

``` 
pcc@Ubuntu:/webapps/rapidpro-dep/mailroom$ curl -X GET "http://127.0.0.1:8090"
{
  "component": "mailroom",
  "url": "/",
  "version": "5.4.4"
}
pcc@Ubuntu:/webapps/rapidpro-dep/mailroom$ curl -X GET "http://127.0.0.1:8090/mr/"
{
  "component": "mailroom",
  "url": "/mr/",
  "version": "5.4.4"
}
pcc@Ubuntu:/webapps/rapidpro-dep/mailroom$ curl -X GET "http://127.0.0.1:8090/mr/docs/functions.json"
404 page not found ```

Kindly assist..

**Comment by Boxroma** [comment]
<img width="1279" alt="Screenshot 2020-04-10 at 10 51 23" src="https://user-images.githubusercontent.com/6860289/78977913-3a41a180-7b19-11ea-9147-a7aac59bf3f1.png">

**Comment by ericnewcomer** [comment]
The IPs in your details there don't match and aren't necessarily doing the same thing. I would start by trying to hit the exact URL the editor is trying to in the console.

As this is a configuration issue, please use the mailing list for help going forward, thanks:
https://groups.google.com/forum/#!forum/rapidpro-dev
