### ISSUE TITLE
Organize task packages in a top-level tasks directory?

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#164]
Just thinking there's a lot going on at the top-level and for someone like myself not so familiar with the codebase it would be helpful to easily see what the different tasks are.

**Comment by nicpottier** [comment]
Ya, I like that. There's actually a bunch of other cleanup things I'd like to do but they would be virtually instant if the go tools ever get fixed and hours of mucking about to do them manually and I just can't bring myself to do it manually.
