### ISSUE TITLE
Better error messages from BulkSQL failures

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#190]
Not sure what we can do here but right now I'm looking at https://sentry.io/organizations/nyaruka/issues/1289392268/?project=1281372 and wishing it had even a little a little bit more context... maybe the first X chars of the SQL could be included in the error message?

**Comment by nicpottier** [comment]
Ya, certainly worth putting in the SQL, though I think the problem is that the SQL just has parameters so you'd have to include those as well. But certainly worth exploring more.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/mailroom/pull/452  and af2e5843d365a6943a415f9b417a276c40c8c060
