### ISSUE TITLE
Use header to indicate webhook calls are made during simulation

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#192]
As of #191 simulation uses a different goflow engine instance which provides a simple way to have simulated sessions use different services.. and webhooks are a service. So instead of the goflow webhook service taking a User-Agent string, it would take a map of default headers to add to any request.

Which could include `X-RapidPro-Simulation` header.. giving users with their own webhook services the option to handle simulator calls differently.

**Comment by nicpottier** [comment]
Ya this is a nice thing for sure.

**Comment by rowanseymour** [comment]
Added in #201
