### ISSUE TITLE
Switch to repeatable read transactions

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/mailroom#22]
https://www.postgresql.org/docs/9.6/static/transaction-iso.html

**Comment by dodobas** [comment]
why is this a requirement ?

**Comment by nicpottier** [comment]
It isn't necessarily, but it seems the closest to what we want. (and honestly how I expect a transaction to work)

**Comment by nicpottier** [comment]
After seeing this run a while I'm going to say we don't need this unless we start seeing cases that tells us otherwise, closing.
