### ISSUE TITLE
Inspecting missing dependencies

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#225]
Currently on a save, RapidPro calls the /flow/inspect endpoint. This reads the flow which errors if it is structurally invalid (we want to keep that).

The response is the output from calling `Inspect` on the flow, e.g.

```json
{
    "dependencies": {
        "groups": [
            {
                "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
                "name": "Testers"
            }
        ]
    },
    "results": [
        {
            "key": "answer",
            "name": "Answer",
            "categories": [],
            "node_uuids": [
                "6fde1a09-3997-47dd-aff0-92e8aff3a642"
            ]
        }
    ],
    "waiting_exits": [],
    "parent_refs": []
}
```

However if we passed it a `validate_with_org_id` in the request.. it calls `CheckDependencies`, which might result in the end returning an error as the response, e.g.

```json
{
    "error": "flow failed validation: missing dependencies: field[key=birthdate,name=],group[uuid=1465eb20-066d-4933-a8b4-62fe7b19fd39,name=I Don't Exist]"
}
```

If we want this endpoint to just tell us which dependencies are missing rather than erroring, should we just stick a flag on each dependency reference? E.g. 

```
{
    "dependencies": {
        "groups": [
            {
                "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
                "name": "Testers",
                "missing": true
            }
        ]
    },
    ...
}
```

**Comment by ericnewcomer** [comment]
Interesting that you should say this, I was just having this exact thought. I much prefer the second option with structural feedback for anything missing. This will allow us to not have the dependency checking logic in both places to ensure what we show matches how we execute.

**Comment by rowanseymour** [comment]
To be clear that's one option - the other is what we do now. A second option would be to call these missing dependencies out separately, e.g.

```
{
    "dependencies": {
        "groups": [
            {
                "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
                "name": "Testers"
            },
            {
                "uuid": "01b3b26d-c0fe-4967-8a98-5be3ce10e870,
                "name": "Customers"
            }
        ]
    },
    "missing_dependencies": {
        "groups": [
            {
                "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
                "name": "Testers"
            }
        ]
    },
    ...
}
```

Which is obviously more repetitive.. but it has the nice property of not adding state to the asset references. Asset references are used throughout the flow definition where they don't have the `missing` property, and we need them to serialize without it.

**Comment by nicpottier** [comment]
I'm personally fine with either. Seems that the argument towards having two lists is mostly an implementation detail that could be solved in other ways (specifically `missing` could be a pointer to a boolean that has `omitempty`?) Doesn't seem like we should be making API kind of decisions based on that though.

**Comment by ericnewcomer** [comment]
Honestly my only real concern is that it be a structured response. From an API standpoint a single list feels more right, but again, not that important to me.

**Comment by rowanseymour** [comment]
I don't disagree with that and really it could just be a regular boolean with `omitempty` that only appears when it's `true`.. which it wouldn't be unless you'd called `Inspect`. The bit I don't like is that references would now have this property `Missing` which returns a potentially wrong result depending on whether the flow has been inspected. You have to remember if you're looking at an asset reference in an action that you can't trust the value of `Missing`...

But that wouldn't be the end of the world and there are other ways to solve this... so if I can make the single list work I would prefer that.

**Comment by nicpottier** [comment]
Wouldn't it being a pointer address that? IE, `nil` means we don't know if it is missing or not?

**Comment by rowanseymour** [comment]
Yeah I suppose so.. ok will have a go now at option 1..

**Comment by rowanseymour** [comment]
One problem is that the references are part of the supposedly _immutable_ flow definition. Soon as you add state that serializes, you've changed how that flow serializes. For example, the migrate endpoint in mailroom - it inspects the flow and returns it to be serialized. Now the flow definition is full of `"missing": true`.. trying to think of other ways to do this...

**Comment by rowanseymour** [comment]
The way I've gone with this is a wrapper struct that adds `missing` as a field once the thing has been inspected. I like this better because it's not adding state to the flow definition.

But it does have me now weighing up the pros and cons of flattening the list of dependencies since we could also add a field called `type`, e.g.

```
"dependencies": {
  "groups": [
    {
      "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
      "name": "Testers",
      "missing": true
    },
    {
      "uuid": "01b3b26d-c0fe-4967-8a98-5be3ce10e870,
      "name": "Customers"
    }
  ],
  "labels": [
    {
      "uuid": "4f1aa56f-13a9-4ccd-b41e-26b87a766dd7",
      "name": "Spam"
    }
  ]
}
```

vs 

```
"dependencies": [
  {
      "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
      "type": "group",
      "name": "Testers",
      "missing": true
  },
  {
      "uuid": "01b3b26d-c0fe-4967-8a98-5be3ce10e870,
      "type": "group",
      "name": "Customers"
  }
  {
      "uuid": "4f1aa56f-13a9-4ccd-b41e-26b87a766dd7",
      "type": "label",
      "name": "Spam"
  }
]
```

But also, thinking about some stuff @ericnewcomer said about the editor being able to direct users to where the missing things are, maybe I need to another field.. something like...

```
"dependencies": [
  {
      "uuid": "5e9d8fab-5e7e-4f51-b533-261af5dea70d",
      "type": "group",
      "name": "Testers",
      "missing": true,
      "node_uuids": [
        "c2551ca2-bac0-48f5-9937-051463114bf0",
        "61de3776-e4ae-4929-bd89-98b0d52b111e"
      ]
  },
  {
      "uuid": "01b3b26d-c0fe-4967-8a98-5be3ce10e870,
      "type": "group",
      "name": "Customers",
      "node_uuids": [
        "c2551ca2-bac0-48f5-9937-051463114bf0"
      ]
  }
  {
      "uuid": "4f1aa56f-13a9-4ccd-b41e-26b87a766dd7",
      "type": "label",
      "name": "Spam",
      "node_uuids": [
        "2a1fd66a-2566-4b5b-9500-94554d309365"
      ]
  }
]
```

@nicpottier @ericnewcomer thoughts?

**Comment by nicpottier** [comment]
Knowing where the missing dependencies are certainly looks useful to me, but I would let whatever is easiest for the editor guide the decision of the API, since that is its purpose after all. So whatever @ericnewcomer thinks!

**Comment by rowanseymour** [comment]
Fine with that tho will mention we also consume this API in RP because we have to go save this dependencies in the m2m tables

**Comment by ericnewcomer** [comment]
The editor LOVES having the node uuids there. I mean, can certainly figure it out too, but the having this sort of logic in one place sounds like a big win.

**Comment by rowanseymour** [comment]
This done

**Comment by ericnewcomer** [comment]
One issue I've encountered while consuming this is that this gives us a full dependency report by node, which is great, but the editor still needs to do a lot of work to determine which actions have which failed dependency. For some, it's just inconvenient and inefficient. 

However in one case, this is really unfortunate -- referencing a missing field any place we allow expressions. In this case, the editor needs to inspect and parse all expressions in order to render them as a "missing" thing properly which defeats trying to have this sort of logic in one place. I would very much rather we had action uuids recorded where appropriate for this reason. This goes for messages, quick replies, attachments, webhooks, headers, updating contacts, setting results, etc..

**Comment by rowanseymour** [comment]
Hmm seems pretty silly to have goflow go to the trouble of tracking down where the dependencies are, only for the editor to essentially have to do it again.. so I think we change goflow to return `action_uuids`.
