### ISSUE TITLE
Flow run Timeout issues in Mailroom v5.5.3

### ISSUE THREAD

**Issue by tybritten** [rapidpro/mailroom#279]
This is two issues that might be related:
1) Our catch-all flow has an expiration set to 30mins. there's a sub-flow that has a significantly longer timeout. What used to happen is as long as the sub-flow completed successfully, the flow's timeout would still be respected. So the sub-flow has a 24hr timeout but comes back in 2 mins, the main flow would still timeout in 30. now, the timeout for the parent flow is set to the max timeout of all the sub-flows added together. So in this case, even if that long timeout sub-flow returns in 2mins, the parent flow won't expire for 24hrs 30mins. This is a recent behavior change. 

2) archiver failed to archive some flow runs due to some flows being active. When i look at those runs in the db, they're past their expiration but haven't been expired by mailroom.

**Comment by tybritten** [comment]
Just an update- I checked for flowruns that expired before today but have an exited_on that's null, and I have 3812 of them.

**Comment by nicpottier** [comment]
This is the task in charge of expiring things:
  https://github.com/nyaruka/mailroom/blob/master/tasks/expirations/cron.go

It looks for candidates with this query:
  https://github.com/nyaruka/mailroom/blob/master/tasks/expirations/cron.go#L128

Might be interesting to know how many are matching that. But that should give you what you need to do some digging.

**Comment by tybritten** [comment]
What is the parent_uuid? some of the stragglers have parent_uuids set but i can't find those UUIDs in the db

**Comment by koallann** [comment]
@tybritten as far as I understood `parent_uuid` is the parent flow's UUID.

We are facing the same problem, with 500k+ flow runs that are not expiring, all of them have the `parent_uuid` filled, that's, [expiration tasks](https://github.com/nyaruka/mailroom/blob/master/tasks/expirations/cron.go#L102) are queued for these flow runs.

We also are executing [this query](https://github.com/nyaruka/mailroom/blob/master/tasks/expirations/cron.go#L127) at different times and it always returns the same initial lines.

Mailroom is in `v5.5.17`.

**Comment by johncordeiro** [comment]
@nicpottier did you check if this accumulation of flow runs is happening in your database?

**Comment by nicpottier** [comment]
I had some time to explore this a bit today and made some tweaks to the Mailroom code that does expirations here:
  https://github.com/nyaruka/mailroom/pull/317

Note that in our case we had about 1,800 runs in that state though, so far fewer than what you are seeing. After pushing those changes we are down to about 170 which seem persistent and need further followup to figure out what is occurring. It may be something where either a race condition or a DB hiccup is causing some runs to be left in a state that Mailroom then doesn't consider for expiration (and also doesn't set as inactive)

**Comment by tybritten** [comment]
I realized we talked more about the second issue, but we're still seeing the first issue- run timeouts getting set with a total amount of the timeouts of the sub flows even if they complete quickly. 

Also can we change the default flow timeout for new flows?

**Comment by tybritten** [comment]
I cleaned up our old flowruns a few weeks ago, and just had archiver hit a 'still active' run that should have been expired. I checked,it wasn't expired because it had a parentUUID, and I checked that parent flowrun (and it's parent) and they were both expired. 

If a flowrun is past its expiration but is still active and has a parentUUID, shouldn't we check if that parent has been expired and then expire the run too?

EDIT: We're currently on Mailroom `v5.6.1`

**Comment by tybritten** [comment]
Update: We're still seeing this issue in 6.0.3. I'm not sure I understand why we don't expire flowruns with a parent. If I'm in a sub-flow and it goes past the expiration, why wouldn't we expire that and return to the parent flow?

**Comment by rowanseymour** [comment]
Note that expiration has now been completely reworked to be session based - if a session is in `status=WAITING` then it needs to have `wait_expires_on` set, and when we set that we look to see if the waiting run in the session has a parent to determine whether `wait_resume_on_expire` should be true or false.

So I'm going to optimistically assume whatever was broken here is now... not broken.
