### ISSUE TITLE
Switch to pub/sub for workers instead of polling for new tasks

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/mailroom#30]
Not the biggest of deals but all that polling will start adding up.

**Comment by nicpottier** [comment]
Played with this a bit, it is actually unclear if this would be much better from a redis load point of view. While we do poll every 250ms right now, a pubsub system would mean we would be hitting redis twice as often as new tasks are added. (or essentially n times as many independent mailroom instances). While that reduces the delay before handling a task that may be a bit much. Will revisit.

**Comment by dodobas** [comment]
meh, did not want to do that, reopening

**Comment by nicpottier** [comment]
Closing as I don't think this is obviously better.
