### ISSUE TITLE
Max concurrent event misbehaving

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/mailroom#300]
We've noticed that the channel config that's called `max_concurrent_events`, that's mainly used for IVR channels is not working as expected. 

What happens is that when starting the IVR flow with `max_concurrent_events` enabled, a lot of calls are queued, but it seems that [retryCalls](https://github.com/nyaruka/mailroom/blob/d2c0c72e076fb127073de3f9a5590486071b8604/tasks/ivr/cron.go#L51) is not working properly and all the calls keep in the queue forever. Many contacts never receive a single call.

We're looking deeply the `retryCalls` function to find the problem but I'm creating this issue to double-check if we aren't configuring anything wrong.

**Comment by johncordeiro** [comment]
I've also noticed that actually it's queueing up 1 event per minute, still looking to identify why.

**Comment by nicpottier** [comment]
If you set the concurrent limit to 1 then yes it will only pop one call every one minute when it checks for queued calls, so that part at least is expected.

Curious to hear what you find. This isn't a feature that is used much as it is really only needed when using IVR endpoints that don't do their own queuing so not hard to imagine it isn't perfect.

**Comment by johncordeiro** [comment]
I forgot to mention that it pops one call every minute for higher max_concurrent_events.

**Comment by johncordeiro** [comment]
This [validation](https://github.com/nyaruka/mailroom/blob/3e64ad1ef21a8d61e60116b1b3eed0fac9ccc57a/tasks/ivr/cron.go#L71) is making retry to work just for one connection per channel, once this connection is executed, its channel is added to the dictionary in this [line](https://github.com/nyaruka/mailroom/blob/d2c0c72e076fb127073de3f9a5590486071b8604/tasks/ivr/cron.go#L109) and all other connections for the same channel are queued up again from this point on, in this case, because every minute `retryCalls` is triggered it just executes one connection from that channel.

Do you know why the rule of `throttledChannels` was placed?

**Comment by nicpottier** [comment]
So first question would be do you need this throttling? It should only be required if you are using Somleng or some other backend that doesn't do it's own queueing.

That code looks reasonable to me, what are you saying looks wrong there?

**Comment by johncordeiro** [comment]
1. We've checked that call starts without any queue from the backend (in this case, we're using Somleng) for about 3000 phone numbers, it leads RapidPro database to very high CPU usage.

2. Concurrent max events seems to be a good solution, but what's wrong is for example, when starting for 3000 contacts with `max_concurrent_events` = 100, it sends the first batch and queue up the other 2900 calls. What's happening is that because of the logic I've explained, these 2900 calls are just executed 1 per minute, which means that will end in 2900 minutes or ~48 hours.

**Comment by nicpottier** [comment]
Unless they have changed, Somleng doesn't have any internal queueing, so they just fail all the calls past the lines they have. But maybe that's changed.

Happy to accept a PR if you want to play with this, we don't have anybody using Somleng so don't have much visibility into how this should work ideally.
