### ISSUE TITLE
Activity blocking for suspended orgs

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#302]
Currently we block handling of incoming messages but think we also need to block..

 * Scheduled broadcasts
 * Campaign events
 * Incoming IVR calls 

Other things can be blocked from being initiated on the RP UI side like broadcasts and flow starts.. tho maybe mailroom should still refuse to do them?

**Comment by nicpottier** [comment]
Campaign events bring up an interesting point actually. In that if we don't start the flow when they are suspended then their series of messages could get munged up in a way that isn't obvious when they start again.

That kind of leads me back to maybe we should be running the flows but not sending the messages for suspended orgs? (either failing or putting them in a failed state)

Maybe worth a call to chat with @ericnewcomer ?

**Comment by rowanseymour** [comment]
We chatted and consensus is to have mailroom continue handling everything for a suspended org and make it a UI thing instead (see https://github.com/rapidpro/rapidpro/issues/1243). Going to undo change to have mailroom refuse to handle incoming messages for suspended orgs made in https://github.com/nyaruka/mailroom/pull/301.
