### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by heniotierra** [rapidpro/mailroom#319]
I get this error when I run `go build github.com/nyaruka/mailroom` (mailroom latest version) with golang v1.14.6:

> github.com/nyaruka/mailroom/models
> ../../../go/src/github.com/nyaruka/mailroom/models/contacts.go:272:34: cannot use results.Hits.TotalHits (type *elastic.TotalHits) as type int64 in return argument

**Comment by rowanseymour** [comment]
It looks like you're building against a different version of Elastic search than v6.2.33 that is set in go.mod
