### ISSUE TITLE
Switching from classifier_called to service_called in Mailroom v5.5.13+ may have introduced critical bugs

### ISSUE THREAD

**Issue by koallann** [rapidpro/mailroom#323]
The switch from `classifier_called` to `service_called` in update to Mailroom v5.5.13+ (Goflow v0.85.0+) may have introduced critical bugs for contact's incoming messages and expiration/timeout tasks depending on your database.

The point is that the `runner.ResumeFlow(...)`  [passes](https://github.com/nyaruka/mailroom/blob/b0fb19a1c8b7905466ade9badc69fcbc50a46c9a/runner/runner.go#L81) the contact's session to the Goflow, which in its turn reads the session `output` by iterating each run and for each run, its events are read by validating the event type, which must be included in [flows.events.base.registeredTypes](https://github.com/nyaruka/goflow/blob/2364b9206562393f72d1af838c384389a7d248cb/flows/events/base.go#L14), otherwise the flow resume will fail, so the contacts with `classifier_called` events in their session outputs will go into the following bugs after a Mailroom v5.5.13+ update:

- If a flow is waiting for response and the contact just tries to respond;
- The previous problem may be solved automatically by flow expiration unless the contact is in a child flow, because it will be necessary to resume the flow and if there is a lot of flow runs in that state, the expiration cron will be stuck trying to expire the oldest 25k flow runs;
- The same for timeouts regardless the contact is in a parent/child flow.

### How to reproduce

1. Running the Mailroom in v5.5.12, create a flow that calls a classifier and waits for a contact response at the end, something like:

![image](https://user-images.githubusercontent.com/24883556/88545167-fb185d00-cff0-11ea-8bfb-97f890319c54.png)

2. Start the flow for a contact, go through a `Split by intent` node and let the flow waiting for a response;
3. Stop the Mailroom, switch it to v5.5.13 and run it again;
4. Try to respond the flow.

I made this simple fix: https://github.com/nyaruka/goflow/compare/master...Ilhasoft:hotfix/classifier_called, but should this be in a RP's django migration?

**Comment by rowanseymour** [comment]
Hmm yeah sorry this is a bug. We switched from `classifier_called` to `service_called` during 5.5 development but we didn't remove `classifier_called` until we were sure all older sessions with that event were finished. I think the fix here is to just put it back and only remove it once we're sure no-one needs it any more. Or make it so sessions load with events they don't recognize... I'll try to get a fix for goflow out today.

**Comment by rowanseymour** [comment]
Hey guys, I've made a **v5.6.2** patch release which should now load `classifier_called` events. Please confirm that works for you.

**Comment by koallann** [comment]
Hey @rowanseymour, that patch worked well for us, thanks!
