### ISSUE TITLE
Need to trim external ID when creating Msgs? (or make Msg.external_id TEXT)

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/mailroom#338]
Not POSITIVE this is external this is external ID since we are committing many things but that's my suspicion:

```

pq: value too long for type character varying(255) 
error during bulk query github.com/nyaruka/mailroom/models.BulkSQL 	/home/runner/work/mailroom/mailroom/models/utils.go:136 
github.com/nyaruka/mailroom/models.InsertMessages 	/home/runner/work/mailroom/mailroom/models/msgs.go:417 
github.com/nyaruka/mailroom/hooks.(*CommitMessagesHook).Apply 	/home/runner/work/mailroom/mailroom/hooks/msg_created.go:166
--
```

**Comment by rowanseymour** [comment]
It's an indexed field so maybe trimming is better.. or we trim what we index on

**Comment by rowanseymour** [comment]
I bet this was attachments. Although we upped attachment length to 2048 in the code... we've never been able to run that migration, so it's still `character varying(255)[]` on both prod dbs.

**Comment by rowanseymour** [comment]
Update: we finally succeeded in running `ALTER TABLE "msgs_msg" ALTER COLUMN "attachments" TYPE varchar(2048)[] USING "attachments"::varchar(2048)[];`

Should make sure goflow never hands mailroom a message with attachments that are longer than 2048 chars: https://github.com/nyaruka/goflow/issues/1000
