### ISSUE TITLE
Error: cannot use results.Hits.TotalHits (type *elastic.TotalHits) as type int64 in return argument

### ISSUE THREAD

**Issue by xkmato** [rapidpro/mailroom#367]
When I run `go build github.com/nyaruka/mailroom/cmd/mailroom` I get the error 

`# github.com/nyaruka/mailroom/core/models
go/src/github.com/nyaruka/mailroom/core/models/search.go:113:34: cannot use results.Hits.TotalHits (type *elastic.TotalHits) as type int64 in return argument`

**Comment by rowanseymour** [comment]
See https://groups.google.com/g/rapidpro-dev/c/-0s37vENbXU .. basically don't use `go get`
