### ISSUE TITLE
Simulator doesn't honor "ignore keywords in this flow"

### ISSUE THREAD

**Issue by putorti** [rapidpro/mailroom#371]
Checking the box on the flow doesn't seem to affect the simulator, keywords will still work.

**Comment by ericnewcomer** [comment]
Looked into this and reproduced it. I didn't dig into it, but I believe this logic is inside the mailroom.

**Comment by rowanseymour** [comment]
Can confirm - we clone flows that we simulate, but we're not cloning the "ignore keywords" setting.. making a fix..
