### ISSUE TITLE
WriteUpdatedSession allocating a lot of memory

### ISSUE THREAD

**Issue by koallann** [rapidpro/mailroom#385]
In the last days we're facing Mailroom (v5.7.24) k8s pods reaching their memory limits intermittently, 2GB, even after increasing from 1GB, what led me to check the memory in this scenario of high memory usage. So, I enabled the [pprof](https://golang.org/pkg/net/http/pprof/) tool on the application for analyze it running in production, trying to catch some memory leak.

I did some heap dumps, the following is one of them considering the `inuse_space` indice:

![image](https://user-images.githubusercontent.com/24883556/100355895-48253380-2fd1-11eb-82a1-3dedfcf9f2de.png)

There's a lot of allocated memory in the `bytes.makeSlice` node, that's reached from `WriteUpdatedSession` node, and checking the [runs.go#WriteUpdatedSession](https://github.com/nyaruka/mailroom/blob/v5.7.24/models/runs.go#L461) we can see some JSON decoding operations on the `FlowSession` type, which can contain a lot of flow runs with a lot of events. I also noticed the heap metric (sampling of memory allocations of live objects) from the `/debug/pprof/` just increasing until it reached the memory limit, perhaps the many allocations on the heap giving more work to the GC and a bad `GOGC` value (we're running with the default, 100).

Do you have any recommendation for serving Mailroom in this scenario of many flow runs/events being processed every time? Like a relation for `GOGC` variable value.

You can download the heap dump [here](https://drive.google.com/file/d/1aRfq1gtjKoIPQtB7VOQ_lUQAl9c8RaJ9/view?usp=sharing).

**Comment by rowanseymour** [comment]
Interesting.. we've not run into such problems. For RapidPro hosting we run two instances of mailroom on two boxes with 30GB memory (each box also runs RapidPro, Courier etc) so have a lot more headroom. 

Flow sessions can get big which is why we're always enforcing limits on things like number of steps, size of webhook payloads etc. Have you changed anything like that which might be leading to exceptionally big session JSON blobs?

**Comment by nicpottier** [comment]
As Rowan noted, I don't think we really are targeting a VM only having a gig of space, especially at peak usage. At first glance this does look like `makeSlice` is grabbing some really big batches of memory and ya, I would guess that is likely related to Session. Note that I imagine makeSlice is doing the usual thing of doubling the size of the inner buffer when it runs out of room:
  https://golang.org/src/bytes/buffer.go#L117

So the buffer is possibly going to 144MB when it really only needs 70MB or the like.

But ya, I'd be curious where these giants buffers are coming from.. looks like JSON marshalling?

**Comment by koallann** [comment]
Hi @rowanseymour @nicpottier sorry for the delay... we spend a more time on this and found the cause: we have an org with 6 contacts being [WhatsApp Business App](https://www.whatsapp.com/business/?lang=en) numbers replying automatically any message, that's, they were in an infinite conversation with us. Mailroom normalized after blocking these contacts, I think this could be a WhatsApp failure too because a WhatsApp Business API number can't send messages to another Business API number, but from a Business API number to a Business App number and vice-versa is allowed.

**Comment by nicpottier** [comment]
Ah.. ya,  message loops can cause all sorts of problems! Ok, closing then.
