### ISSUE TITLE
Import more than 20,000 contacts

### ISSUE THREAD

**Issue by nanopn** [rapidpro/mailroom#391]
When i try to import more than 20,000 contacts, mailroom show this: 

`ERRO[0326] error running task                            error="unable to load contact import batch with id 8213: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8213}" task_type=import_contact_batch worker_id=3
INFO[0326] task complete                                 elapsed="866.207µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=3
ERRO[0326] error running task                            error="unable to load contact import batch with id 8214: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8214}" task_type=import_contact_batch worker_id=2
INFO[0326] task complete                                 elapsed="811.445µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=2
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=0
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=3
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=2
ERRO[0326] error running task                            error="unable to load contact import batch with id 8215: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8215}" task_type=import_contact_batch worker_id=1
INFO[0326] task complete                                 elapsed=1.363313ms org_id=4 queue=batch task_type=import_contact_batch worker_id=1
ERRO[0326] error running task                            error="unable to load contact import batch with id 8216: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8216}" task_type=import_contact_batch worker_id=0
INFO[0326] task complete                                 elapsed="926.239µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=0
ERRO[0326] error running task                            error="unable to load contact import batch with id 8218: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8218}" task_type=import_contact_batch worker_id=2
INFO[0326] task complete                                 elapsed="662.659µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=2
ERRO[0326] error running task                            error="unable to load contact import batch with id 8217: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8217}" task_type=import_contact_batch worker_id=3
INFO[0326] task complete                                 elapsed="945.548µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=3
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=1
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=0
ERRO[0326] error running task                            error="unable to load contact import batch with id 8219: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8219}" task_type=import_contact_batch worker_id=1
INFO[0326] task complete                                 elapsed="349.404µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=1
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=3
DEBU[0326] sleeping, no tasks                            comp=foreman
ERRO[0326] error running task                            error="unable to load contact import batch with id 8220: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8220}" task_type=import_contact_batch worker_id=0
INFO[0326] task complete                                 elapsed="727.626µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=0
ERRO[0326] error running task                            error="unable to load contact import batch with id 8221: sql: no rows in result set" org_id=4 queue=batch task="{\"contact_import_batch_id\": 8221}" task_type=import_contact_batch worker_id=3
INFO[0326] task complete                                 elapsed="707.672µs" org_id=4 queue=batch task_type=import_contact_batch worker_id=3
INFO[0326] starting handling of task                     org_id=4 queue=batch task_type=import_contact_batch worker_id=1
`

The batches in my database are already created, but I can't understand why the mailroom can't find the ids:

ContactImportBatch object (8213)
ContactImportBatch object (8214)
ContactImportBatch object (8215)
ContactImportBatch object (8216)
ContactImportBatch object (8217)
ContactImportBatch object (8218)
ContactImportBatch object (8219)
ContactImportBatch object (8220)
ContactImportBatch object (8221)
ContactImportBatch object (8222)

sometimes it works and most of the time it doesn't

my configuration is:

`
CONF: Environment overrides:

CONF: Final top level values:
CONF:                                  Address = localhost
CONF:                         AttachmentDomain = 
CONF:                                AuthToken = 
CONF:                           AWSAccessKeyID = 
CONF:                       AWSSecretAccessKey = 
CONF:                             BatchWorkers = 4
CONF:                                       DB = postgres://temba:temba@localhost/temba?sslmode=disable&Timezone=UTC
CONF:                               DBPoolSize = 36
CONF:                       DisallowedNetworks = 127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
CONF:                                   Domain = 
CONF:                                  Elastic = http://localhost:9200
CONF:                                   FCMKey = 
CONF:                           HandlerWorkers = 32
CONF:                             LibratoToken = 
CONF:                          LibratoUsername = 
CONF:                                 LogLevel = error
CONF:                        MailgunSigningKey = 
CONF:                        MaxStepsPerSprint = 100
CONF:                           MaxValueLength = 640
CONF:                                     Port = 8090
CONF:                                    Redis = redis://localhost:6379/15
CONF:                     RetryPendingMessages = true
CONF:                             S3DisableSSL = false
CONF:                               S3Endpoint = https://s3.amazonaws.com
CONF:                         S3ForcePathStyle = false
CONF:                            S3MediaBucket = mailroom-media
CONF:                            S3MediaPrefix = /media/
CONF:                                 S3Region = us-east-1
CONF:                                SentryDSN = 
CONF:                               SMTPServer = 
CONF:                                 UUIDSeed = 0
CONF:                                  Version = 6.1.4
CONF:                    WebhooksBackoffJitter = 0.5
CONF:                   WebhooksInitialBackoff = 5000
CONF:                     WebhooksMaxBodyBytes = 1048576
CONF:                       WebhooksMaxRetries = 2
CONF:                          WebhooksTimeout = 15000
`

Thanks for your help

**Comment by rowanseymour** [comment]
If mailroom isn't seeing the batch objects in the database, is it possible RP is creating them in a transaction? Maybe you have celery as ALWAYS_EAGER on the RapidPro side? So it's creating the batches inside the transaction Django wraps around the web request...

**Comment by nanopn** [comment]
Thanks Rowan,   fixed: 

CELERY_ALWAYS_EAGER = False
CELERY_EAGER_PROPAGATES_EXCEPTIONS = False
BROKER_BACKEND = "redis"

and run in command line: 

celery --workdir=/home/ubuntu/src/rapidpro -A temba  worker --concurrency=10 -n temba_worker -l info 


Saludos
