### ISSUE TITLE
Broadcasts do not trigger Android relayer syncs

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/mailroom#392]
For Android relayers, we fire a sync request via FCM when sending messages. This is currently handled in flows via the `send_messages` hook:
  https://github.com/nyaruka/mailroom/blob/master/core/hooks/send_messages.go#L78
  
  We aren't doing the same when creating messages for broadcasts so those aren't triggering a relayer sync, causing a delay before they are fetched / sent. We should refactor the FCM notification code to be standalone then call it on the broadcast side as well when those messages have been created.

**Comment by rowanseymour** [comment]
Same problem for ticket generated outgoing messages
