### ISSUE TITLE
Store Flow Sessions in S3 instead of DB

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/mailroom#430]
One of the big bottlenecks / expenses in running RapidPro at scale is writing our sessions to the DB. Sessions are big JSON blobs and that's great from a logging perspective but it is a lot of IO on the database side without much benefit. For our largest installs this turns into gigs of data being written/updated on postgres. We also don't really benefit at all from having that data in RDS in that we don't query against it for anything except knowing expirations etc.. S3 would also let us keep sessions around longer (possibly forever) at a very low cost.

Proposal is to move to writing session's `output` field (the session JSON blob) to S3 instead. All other fields would remain the same in our database row.

Challenges:
 1. We now need to write sessions to both the DB (fielded data) and S3 (JSON blob). We need to figure out ordering here and how to do this in a performant manner for batch inserts. (likely goroutines)
 2. How do we name these? Ideally we would store these in a way that could facilitate having a contact history that goes back indefinitely instead of just 90 days. (other things would need to be done, but this would be a first step) That implies a directory structure that is contact centric and that we could use S3 list commands to iterate. IE, something like: `/[org_uuid]/[contact_uuid]/sessions/session_[creation_date]_[session_uuid].json`
  3. Also related to naming how do elegantly deal with failures say at the DB level after a session is written? IE, if we write the S3 session first but then fail on the DB commit? Kind of feels like our sessions should be write only and we try to delete S3 sessions AFTER DB updates succeed. IE, each sprint comes up with a new name. So maybe name is more like `/[org_uuid]/[contact_uuid]/sessions/session_[creation_date]_[sprint_clock]_[session_uuid].json` and that name is stored in the DB as a field on session? `output_filename`?
  4. Others?

**Comment by nicpottier** [comment]
We'll need to migrate to this over time, so perhaps the first logical choice is start writing these only just to test out performance characteristics, we'd still use the DB `output` field for the time being but this would give us the benefit of long term archival to start.

**Comment by nicpottier** [comment]
So some S3 performance details:
  https://aws.amazon.com/blogs/aws/amazon-s3-performance-tips-tricks-seattle-hiring-event/
  
Looks like if you don't do anything with naming then 100 req/s is probably fine, but for bulk starts we will definitely be pushing that. Looks like the way around it is to have the prefix of your filename change. Feels like the best way to do that is probably by leading with the contact UUID. 

But wait, turns out that is out of date:
  https://stackoverflow.com/questions/52443839/s3-what-exactly-is-a-prefix-and-what-ratelimits-apply#:~:text=Amazon%20S3%20automatically%20scales%20to,of%20prefixes%20in%20a%20bucket.
  
This says that the default is closer to 3500 req/s and that prefixes are across the entire path, so having `/[org_uuid]/[contact_uuid]/sessions/session_[creation_date]_[sprint_clock]_[session_uuid].json` probably is just fine since the data is all within the contact uuid.

**Comment by nicpottier** [comment]
Ok, so proposal for path would be:

`/[org_id]/[first 4 of contact uuid]/[contact uuid]/sessions/session_[creation_date]_[last_modified]_[session_uuid].json`

We store the full path as `output_url` in `flows_flowsession`. @rowanseymour thoughts?

**Comment by nicpottier** [comment]
So last thing to work out is the commit/rollback race.

So if we write the S3 sessions first, then that means if we fail, we just rollback the DB transaction, which is fine, that makes sense to me, we can retry later.

The harder issue is what happens if our DB commit fails. At that point we have written to S3, so the file exists in the contact folder despite that session and those events not having taken place. I think the more I think about it the more we should try to avoid ever calling a DELETE or cleaning up within handling or the like. Instead, we should rely on writing the file with the unique name that is tracked within the session. Then when we clean up the session table for completed sessions, we delete all but the "final" session from S3. So basically we don't delete the DB row containing the right filename UNTIL we have made sure there is only one record for that session.

Tricky bit here is if we implement a contact history page that depends on S3 lists to get the sessions (this is some future where we also have msg data in json blobs) then they will have to ignore session objects which exist in the DB but have duplicate sessions in S3. But that seems doable.

**Comment by bearnard** [comment]
👍 would support for other object stores like Redis (with expiry) be beneficial here? (at least that was our first thought when we experience heavy IO in recent project)

**Comment by nicpottier** [comment]
Sessions are too big to put into Redis since Redis really wants to have everything in ram. Having a few million sessions in there would blow it up.

**Comment by bearnard** [comment]
Right, I figured a session generally doesn't last too long and a "running" set might fit just fine, I guess I'm misunderstanding. thanks!

**Comment by bearnard** [comment]
In our recent "scale" event we were at around 40gb per day/1TB per month of db gobbling, which might be more than the average redis.

**Comment by rowanseymour** [comment]
Think we can close this for now as out biggest deployment is now using S3 for all sessions. and we're not seeing any problems 🍾. Configurable by org config setting `session_storage_mode = db|s3`.
