### ISSUE TITLE
Error messages from engine truncated in sentry

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/mailroom#67]
The error message from goflow becomes the `culprit` field and is truncated to 200 chars. The `message` field is always set to `client error` but maybe this could be the full error message. E.g. https://sentry.io/nyaruka/rapidpro-mailroom/issues/861558893/

**Comment by nicpottier** [comment]
Ya, real solution here is getting breadcrumbs working, which may require a bit of work on our side to contribute back to raven / sentry:
  https://github.com/getsentry/raven-go/issues/118

**Comment by rowanseymour** [comment]
What about `SwitchExceptionTypeAndMessage` in logrus_sentry ?

**Comment by nicpottier** [comment]
We could try that, I'm going to play a bit and see if I can make breadcrumbs work this afternoon, sure would be nice to have really good logging of errors before launch.

**Comment by nicpottier** [comment]
FWIW switching on `SwitchExceptionTypeAndMessage` is worse. :(

https://sentry.io/nyaruka/staging-mailrom/issues/861597259/?query=is%3Aunresolved

**Comment by nicpottier** [comment]
Fixed.
